site_name: "CUT! Glemmen Filmfestival"

theme:
  name: dracula
  # Favicon (legg filen i docs/assets/favicon.ico)
  favicon: assets/favicon.ico

markdown_extensions:
  - attr_list
  - toc:
      permalink: ""

nav:
  - Hjem: index.md
  - Filmer som blir vist:
      - Hun som bor i dukken: "/#hun-som-bor-i-dukken"
      - Anosminne: "/#anosminne"
      - Busstoppet: "/#busstoppet"
      - Et Ekko av henne: "/#et-ekko-av-henne"
      - Panel-samtale: "/#panel-samtale"
      - AI tar over verden: "/#ai-tar-over-verden"
      - En Hvit Jul (trailer): "/#en-hvit-jul-trailer"
      - Frost 2 (DUB): "/#frost-2-dub"
      - The Gym Episode 1 & 2: "/#the-gym-episode-1-2"
      - Bursdag p√• Leos: "/#bursdag-pa-leos"
      - Dialogen: "/#dialogen"
      - Selvforsvar Med Karate-Karl: "/#selvforsvar-med-karate-karl"
      - Skogen: "/#skogen"
      - Karl Drais og sykkelen: "/#karl-drais-og-sykkelen"
      - Trailer for Kikis Budservice (Max): "/#trailer-for-kikis-budservice-pa-max"
      - Bad Goodbyes - Southern Outlaws: "/#bad-goodbyes---southern-outlaws"
      - Deltis-kaos: "/#deltis-kaos"
