site_name: CUT! Glemmen Filmfestival

theme:
  name: dracula

site_name: "CUT! Glemmen Filmfestival"

theme:
  name: dracula

nav:
  - Hjem: index.md
  - Program:
      - Hun som bor i dukken: film/hun-som-bor-i-dukken.md
      - Anosminne: film/anosminne.md
      - Busstoppet: film/busstoppet.md
      - Et Ekko av henne: film/et-ekko-av-henne.md
      - Panel-samtale: panel.md
      - AI tar over verden: film/ai-tar-over-verden.md
      - En Hvit Jul (trailer): film/en-hvit-jul-trailer.md
      - Frost 2 (DUB): film/frost-2-dub.md
      - The Gym Episode 1 & 2: film/the-gym-ep-1-2.md
      - Bursdag på Leos: film/bursdag-pa-leos.md
      - Dialogen: film/dialogen.md
      - Selvforsvar med Karate-Karl: film/selvforsvar-karate-karl.md
      - Skogen: film/skogen.md
      - Karl Drais og sykkelen: film/karl-drais-og-sykkelen.md
      - Trailer: "Kikis Budservice" (Max): film/kikis-budservice-trailer.md
      - Bad Goodbyes – Southern Outlaws: film/bad-goodbyes-southern-outlaws.md
      - Deltis-kaos: film/deltis-kaos.md
