[project]
name = "cutfilmfestival-github-io"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14.0"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-dracula-theme>=1.0.8",
]
